### ISSUE TITLE
Please provide ZendeskApi_v2 Create Ticket with Tags also sample Code in VB.net or C#

### ISSUE THREAD

**Issue by shashikant2011** [eneifert/ZendeskApi_v2#116]
Hi,

Please give me a sample code to create ticket including tags also using zendeskapi_v2 in VB.net or C#

Thanks,
SHASHIKANT

**Comment by eneifert** [comment]
Yep no problem you can check out the [readme](https://github.com/eneifert/ZendeskApi_v2) or the [tests](https://github.com/eneifert/ZendeskApi_v2/tree/master/Tests) for plenty of examples.

Happy new year,
Eric

**Comment by eneifert** [comment]
Ah seems the tests don't use the Tags property, so my apologies. But tags are just a list of strings so you could create them like this:

var ticket = new Ticket()
                             {
                                 Subject = "my printer is on fire",
                                 Comment = new Comment() { Body = "HELP" },
                                 Priority = TicketPriorities.Urgent,
                                 Tags = new List<string>() { "yo", "help"}
                             };
