### ISSUE TITLE
Failing HelpCenter Unit Tests

### ISSUE THREAD

**Issue by sitefinitysteve** [eneifert/ZendeskApi_v2#128]
I'm trying to flesh out the HelpCenter API section, but the Unit tests just keep failing 

Example: https://csharpapi.zendesk.com/api/v2/help_center/articles.json

Is there just no HelpCenter active on the account? ...should I be contacting Zendesk instead?

**Comment by sitefinitysteve** [comment]
I contacted Zendesk and they said it needs to be active\created.  Is there any way to get an account, or for you to perhaps just enable the HelpCenter?  

Th response was "May I have you navigate into the account and create the help center? It only has to be a basic one. You may do this by clicking on the life preserver ring in the bottom left corner of the screen"

**Comment by sitefinitysteve** [comment]
Will close, noticed the login is in the Settings.cs

**Comment by eneifert** [comment]
Yep that is why it is there :)
