### ISSUE TITLE
Project will not build?

### ISSUE THREAD

**Issue by ebuychance** [eneifert/ZendeskApi_v2#131]
I just pulled the latest and it throws about 90 build errors related to translations, IVotes, IComments, ArticleSortingOptions, ArticleSearchResults and many more... most errors are "are you missing an assembly reference:

**Comment by ebuychance** [comment]
Looks like the solution file was not updated... the new files are there just not included in the project ;)

**Comment by ebuychance** [comment]
After including all files I see 7 failing tests...

**Comment by eneifert** [comment]
You are correct sir, looks like I didn't check some recent pull requests too carefully. I will look into it and get back to you.

**Comment by eneifert** [comment]
Should be good new.
